
import type { Metadata } from "next";
import { AuthProvider } from "@/context/AuthContetx";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar";
import Footer from '@/components/Footer';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <AuthProvider>
     
      <html lang="en">
        <body className={`${inter.className} bg-yellow-300 `}>
         <NavBar/>
          {children}
          <Footer/>
          </body>
      </html>
    </AuthProvider>
  );
}
